### ISSUE TITLE
英文页面编译有问题

### ISSUE THREAD

**Issue by WaveLong** [DelightRun/ZJUThesis-MPhil#1]
我是在overleaf上使用这个模板，编译thesis.tex会出现一个报错，说\makeECover有问题
![image](https://user-images.githubusercontent.com/31360595/97592294-70099180-1a3b-11eb-825b-5d0e66ce0cb0.png)

**Comment by goksyli** [comment]
remove & at  line 375 in the cls file, and compiling should work

**Comment by DelightRun** [comment]
@WaveLong @goksyli 我没在overleaf上试过，我当时是在本地用xelatex编译的，谢谢指出，我改一下。
